<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.v3_oqqo' shared service.

return $this->services['service_locator.v3_oqqo'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('mailer' => function () {
    $f = function (\AppBundle\service\Mailer $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\service\Mailer']) ? $this->services['AppBundle\service\Mailer'] : $this->load('getMailerService.php')) && false ?: '_'});
}));
