<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSay36rb\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSay36rb/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSay36rb.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSay36rb\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerSay36rb\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Say36rb',
    'container.build_id' => 'e40bbbb0',
    'container.build_time' => 1528897400,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerSay36rb');
